theme: jekyll-theme-cayman
title: [Cazadoras de Estrellas]
description: [Descripción del proyecto: Cazadoras de Estrellas es un grupo de estudiantes de Astronomía
de la Universidad de Chile que realizan actividades para promover la carrera científica en alumnas de enseñanza media.]
